tags:
- name: Estadios
  description: Endpoints de Estadios
- name: Ciudades
  description: Endpoints de Ciudades
paths:
# [GET] satdiums
  /stadiums:
    get:
      tags:
      - Estadios
      summary: Encontrar todos los Estadios
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] satdiums
  /stadiums/{id}:
    post:
      tags:
      - Estadios
      summary: Agregar nuevo Estadios a una Ciudad
      parameters:
      - name: id
        in: path
        description: ID de la ciudad al que se agregará el estadio
        required: true
        type: string
      - name: body
        in: body
        description: Información del estadio
        required: true
        schema:
          $ref: '#/definitions/stadiums'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] stadiums/id
    get:
      tags:
      - Estadios
      summary: Buscar por el id del estadio
      parameters:
      - name: id
        in: path
        description: Id del estadio
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] stadiums/id
    put:
      tags:
      - Estadios
      summary: Actualizar el estadio por el id
      parameters:
      - name: id
        in: path
        description: Id del estadio
        required: true
      - name: body
        in: body
        description: Información del estadio
        required: true
        schema:
          $ref: '#/definitions/stadiums'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] stadiums/id
    delete:
      tags:
      - Estadios
      summary: Elimina el estadio por el id
      parameters:
      - name: id
        in: path
        description: Id del estadio
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] city
  /city:
    get:
      tags:
      - ciudades
      summary: Obtener todas las ciudades
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] city
    post:
      tags:
      - ciudades
      summary: Agregar nueva ciudad
      parameters:
      - name: body
        in: body
        description: Información de la ciudad
        required: true
        schema:
          $ref: '#/definitions/city'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] city/id
  /city/{id}:
    get:
      tags:
      - Ciudades
      summary: Buscar por el id de la ciudad
      parameters:
      - name: id
        in: path
        description: Id de la ciudad
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] city/id
    put:
      tags:
      - Ciudades
      summary: Actualizar la informacion de la ciudad por el id
      parameters:
      - name: id
        in: path
        description: Id de la ciudad
        required: true
      - name: body
        in: body
        description: Información de la ciudad
        required: true
        schema:
          $ref: '#/definitions/city'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] city/id
    delete:
      tags:
      - Ciudades
      summary: Elimina la ciuadad por el id
      parameters:
      - name: id
        in: path
        description: Id de la ciudad
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# definitions
definitions:
  stadiums:
    type: object
    required:
        - id
        - name
        - capacity
        - team
    properties:
      id:
        type: Number
        description: id del estadio
        default: 21490
      name:
        type: string
        description: nombre del estadio
        default: NameStadium
      capacity:
        type: Number
        description: capacidad de espectadores del estadio
        default: 90000
      team:
        type: string
        description: nombre del club que juega en el estadio
        default: nameTeam
  city:
    type: object
    required:
        - department_name
        - description
        - stadiums
    properties:
      department_name:
        type: string
        description: nombre del departamento
        default: Pruebas
      description:
        type: string
        description: descripción del departamento
        default: Donde se hacen las pruebas
      stadiums:
        type: array
        description: Lista de estadios en el departamento
        items:
          $ref: '#/definitions/stadiums'
        default: []
schemes:
 - https
 - http