tags:
- name: Estadios
  description: Endpoints de Estadios
- name: Ciudades
  description: Endpoints de Ciudades
paths:
# [GET] stadiums
  /stadiums:
    get:
      tags:
      - Estadios
      summary: Encontrar todos los Estadios
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] stadiums
  /stadiums/{id}:
    post:
      tags:
      - Estadios
      summary: Agregar nuevo Estadios a una Ciudad
      parameters:
      - name: id
        in: path
        description: ID de la ciudad al que se agregará el estadio
        required: true
        type: string
      - name: body
        in: body
        description: Información del estadio
        required: true
        schema:
          $ref: '#/definitions/stadiums'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] stadiums/id
    get:
      tags:
      - Estadios
      summary: Buscar por el id del estadio
      parameters:
      - name: id
        in: path
        description: Id del estadio
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] stadiums/id
    put:
      tags:
      - Estadios
      summary: Actualizar el estadio por el id
      parameters:
      - name: id
        in: path
        description: Id del estadio
        required: true
      - name: body
        in: body
        description: Información del estadio
        required: true
        schema:
          $ref: '#/definitions/stadiums'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] stadiums/id
    delete:
      tags:
      - Estadios
      summary: Elimina el estadio por el id
      parameters:
      - name: id
        in: path
        description: Id del estadio
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] city
  /city:
    get:
      tags:
      - Ciudades
      summary: Obtener todas las ciudades
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] city
    post:
      tags:
      - Ciudades
      summary: Agregar nueva ciudad
      parameters:
      - name: body
        in: body
        description: Información de la ciudad
        required: true
        schema:
          $ref: '#/definitions/city'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] city/id
  /city/{id}:
    get:
      tags:
      - Ciudades
      summary: Buscar por el id de la ciudad
      parameters:
      - name: id
        in: path
        description: Id de la ciudad
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] city/id
    put:
      tags:
      - Ciudades
      summary: Actualizar la informacion de la ciudad por el id
      parameters:
      - name: id
        in: path
        description: Id de la ciudad
        required: true
      - name: body
        in: body
        description: Información de la ciudad
        required: true
        schema:
          $ref: '#/definitions/city'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] city/id
    delete:
      tags:
      - Ciudades
      summary: Elimina la ciuadad por el id
      parameters:
      - name: id
        in: path
        description: Id de la ciudad
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# definitions
definitions:
  stadiums:
    type: object
    required:
        - id
        - name
        - capacity
        - team
    properties:
      id:
        type: Number
        description: id del estadio
        default: 1
      name:
        type: string
        description: nombre del estadio
        default: Wembley
      capacity:
        type: Number
        description: capacidad de espectadores del estadio
        default: 90000
      team:
        type: string
        description: nombre del club que juega en el estadio
        default: Selección de Inglaterra
      city:
        type: ObjectId
        description: id que referencia la ciudad donde se ecuentra el estadio.
        items:
          $ref: '#/definitions/city'
        default: 656fba46e916cdcb0a577102
  city:
    type: object
    required:
        - id
        - name
        - country
        - stadiums
    properties:
      id:
        type: Number
        description: id de la ciudad
        default: 1
      name:
        type: string
        description: nombre de la ciudad
        default: London
      country:
        type: string
        description: nombre del pais donde se localiza la ciudad
        default: Inglaterra
      stadiums:
        type: array
        description: Lista de estadios que se encuentran en la ciudad
        items:
          $ref: '#/definitions/stadiums'
        default: []
schemes:
 - https
 - http